[package]
name = "memotree"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
valu3 = "0.5.2"
regex = "1.10.2"
byte = "0.2.7"
pest="2.7.11"
pest_derive="2.7.11"